language: node_js

services:
  - elasticsearch

before_script:
  - sleep 10

node_js:
  - "node"

script:
  - npm install -g serverless

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
